export type WfIconName =
    | 'bolt'
    | 'book'
    | 'check'
    | 'clock'
    | 'code'
    | 'copy'
    | 'close'
    | 'folder'
    | 'play'
    | 'refresh'
    | 'rocket'
    | 'search'
    | 'settings'
    | 'sliders';
