import type { DemoCase } from './interface';

export const DEMO_CASES: readonly DemoCase[] = [
    {
        id: 'legacy-path-fallback',
        group: 'Legacy fallback',
        title: 'Shorter path candidate',
        description: 'The most specific file is missing, so the next matching path supplies the response.',
        method: 'GET',
        path: '/api/demo/legacy/users/42',
        responseKind: 'json',
        expectedStatus: 200,
    },
    {
        id: 'method-precedence',
        group: 'Legacy fallback',
        title: 'Method-specific file',
        description: 'POST_orders.json takes precedence over the generic orders.json file.',
        method: 'POST',
        path: '/api/demo/orders',
        responseKind: 'json',
        expectedStatus: 200,
        body: { article: 'DEMO', quantity: 1 },
    },
    {
        id: 'default-json',
        group: 'JSON & files',
        endpointId: 'json-response',
        title: 'Default without a selection',
        description: 'Without a scenario cookie, the regular dynamic file lookup is used.',
        method: 'GET',
        path: '/api/demo/json',
        responseKind: 'json',
        expectedStatus: 200,
    },
    {
        id: 'explicit-json',
        group: 'JSON & files',
        endpointId: 'json-response',
        scenarioId: 'explicit-file',
        title: 'Explicit scenario file',
        description: 'The scenario points directly to another JSON file in the mock directory.',
        method: 'GET',
        path: '/api/demo/json',
        responseKind: 'json',
        expectedStatus: 200,
    },
    {
        id: 'text-response',
        group: 'JSON & files',
        endpointId: 'text-document',
        scenarioId: 'text',
        title: 'Text response',
        description: 'A TXT file is read as plain text with epFetchText.',
        method: 'GET',
        path: '/api/demo/text',
        responseKind: 'text',
        expectedStatus: 200,
    },
    {
        id: 'pdf-response',
        group: 'JSON & files',
        endpointId: 'pdf-document',
        scenarioId: 'pdf',
        title: 'PDF-Download',
        description: 'A real PDF is loaded with epFetchBlob and then offered as a download.',
        method: 'GET',
        path: '/api/demo/pdf',
        responseKind: 'blob',
        expectedStatus: 200,
        downloadName: 'local-mock-api-demo.pdf',
    },
    {
        id: 'bad-request',
        group: 'HTTP-Status',
        endpointId: 'http-errors',
        scenarioId: 'bad-request',
        title: 'Bad Request',
        description: 'The response intentionally returns HTTP 400 with a JSON error body.',
        method: 'GET',
        path: '/api/demo/errors',
        responseKind: 'json',
        expectedStatus: 400,
    },
    {
        id: 'server-error',
        group: 'HTTP-Status',
        endpointId: 'http-errors',
        scenarioId: 'server-error',
        title: 'Internal Server Error',
        description: 'The fetch helper rejects the JSON response with HTTP 500.',
        method: 'GET',
        path: '/api/demo/errors',
        responseKind: 'json',
        expectedStatus: 500,
    },
    {
        id: 'no-content',
        group: 'HTTP-Status',
        endpointId: 'no-content',
        scenarioId: 'empty',
        title: 'No Content',
        description: 'HTTP 204 is served from an empty file without a response body.',
        method: 'GET',
        path: '/api/demo/no-content',
        responseKind: 'text',
        expectedStatus: 204,
    },
    {
        id: 'delay-immediate',
        group: 'Latency',
        endpointId: 'delay',
        scenarioId: 'immediate',
        title: 'No delay',
        description: 'The immediate scenario serves the same file without an artificial delay.',
        method: 'GET',
        path: '/api/demo/delay',
        responseKind: 'json',
        expectedStatus: 200,
    },
    {
        id: 'delay-short',
        group: 'Latency',
        endpointId: 'delay',
        scenarioId: 'short',
        title: 'Short delay',
        description: 'The short scenario delays the same response by 200 milliseconds.',
        method: 'GET',
        path: '/api/demo/delay',
        responseKind: 'json',
        expectedStatus: 200,
    },
    {
        id: 'delay',
        group: 'Latency',
        endpointId: 'delay',
        scenarioId: 'long',
        title: 'Long delay',
        description: 'The long scenario delays the same response by 1000 milliseconds.',
        method: 'GET',
        path: '/api/demo/delay',
        responseKind: 'json',
        expectedStatus: 200,
    },
    {
        id: 'automatic-file',
        group: 'Latency',
        endpointId: 'automatic-file',
        scenarioId: 'candidate-search',
        title: 'Scenario without a file',
        description: 'Status and delay come from the scenario while the file still uses candidate lookup.',
        method: 'GET',
        path: '/api/demo/automatic',
        responseKind: 'json',
        expectedStatus: 200,
    },
    {
        id: 'alternate-mode-fallback',
        group: 'Manifest fallback',
        title: 'Legacy despite manifest errors',
        description: 'Works with a normal, missing, or intentionally invalid manifest.',
        method: 'GET',
        path: '/api/demo/legacy',
        responseKind: 'json',
        expectedStatus: 200,
    },
] as const;
