import type { PlaygroundRequest } from './interface.js';

export const PLAYGROUND_TAG_NAME = 'wf-mock-proxy-playground';

export const PLAYGROUND_REQUESTS: readonly PlaygroundRequest[] = [
    {
        id: 'root-method-fallback',
        group: 'Naming conventions',
        label: 'Root-level method fallback',
        description: 'Resolves mock/PUT_profile.json after more specific candidates are missing.',
        method: 'PUT',
        path: '/api/demo/users/profile',
    },
    {
        id: 'legacy-path-fallback',
        group: 'Naming conventions',
        label: 'Shorter path candidate',
        description: 'Falls back through the request path until a matching file is found.',
        method: 'GET',
        path: '/api/demo/legacy/users/42',
    },
    {
        id: 'method-precedence',
        group: 'Naming conventions',
        label: 'Method-specific file',
        description: 'POST_orders.json wins over the generic orders.json response.',
        method: 'POST',
        path: '/api/demo/orders',
        body: { article: 'DEMO', quantity: 1 },
    },
    {
        id: 'json-response',
        group: 'Files and scenarios',
        label: 'JSON response',
        description: 'Switch between convention lookup and the explicit file in the proxy panel.',
        method: 'GET',
        path: '/api/demo/json',
    },
    {
        id: 'text-response',
        group: 'Files and scenarios',
        label: 'Text response',
        description: 'Returns a plain-text document selected by the manifest.',
        method: 'GET',
        path: '/api/demo/text',
    },
    {
        id: 'pdf-response',
        group: 'Files and scenarios',
        label: 'PDF response',
        description: 'Returns the same binary PDF fixture used by the demo.',
        method: 'GET',
        path: '/api/demo/pdf',
    },
    {
        id: 'http-errors',
        group: 'Response behavior',
        label: 'HTTP errors',
        description: 'Choose between the 400 and 500 response scenarios in the panel.',
        method: 'GET',
        path: '/api/demo/errors',
    },
    {
        id: 'no-content',
        group: 'Response behavior',
        label: 'No content',
        description: 'Returns a real HTTP 204 response without a body.',
        method: 'GET',
        path: '/api/demo/no-content',
    },
    {
        id: 'delay',
        group: 'Response behavior',
        label: 'Artificial latency',
        description: 'Choose immediate, 200 ms, or 1000 ms behavior in the panel.',
        method: 'GET',
        path: '/api/demo/delay',
    },
    {
        id: 'automatic-file',
        group: 'Manifest defaults',
        label: 'Automatic single scenario',
        description: 'The only scenario applies automatically while its file uses convention lookup.',
        method: 'GET',
        path: '/api/demo/automatic',
    },
    {
        id: 'direct-file',
        group: 'Manifest defaults',
        label: 'Minimal explicit file',
        description: 'A path and file are enough for an explicit manifest response.',
        method: 'GET',
        path: '/api/demo/direct-file',
    },
    {
        id: 'direct-no-content',
        group: 'Manifest defaults',
        label: 'Minimal 204 response',
        description: 'A path and status are enough to create an empty response.',
        method: 'GET',
        path: '/api/demo/direct-no-content',
    },
    {
        id: 'endpoint-defaults',
        group: 'Manifest defaults',
        label: 'Endpoint-level settings',
        description: 'Applies file, HTTP status, and delay directly on the endpoint.',
        method: 'GET',
        path: '/api/demo/endpoint-defaults',
    },
    {
        id: 'manifest-fallback',
        group: 'Manifest defaults',
        label: 'Convention fallback',
        description: 'Uses naming conventions even while a valid manifest is present.',
        method: 'GET',
        path: '/api/demo/legacy',
    },
];
